/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type WorkProject = {
  _id: string;
  _type: "workProject";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brand?: string;
  project?: string;
  category?: string;
  date?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blocks?: Array<
    | { _key: string; _type: "photo"; image?: { asset?: { _ref: string; _type: "reference" }; _type: "image" }; variant?: string }
    | { _key: string; _type: "photoRow"; images?: Array<{ asset?: { _ref: string; _type: "reference" }; _type: "image"; _key: string }>; variant?: string }
    | { _key: string; _type: "caption"; label?: string; size?: string; text?: string }
    | { _key: string; _type: "split"; label?: string; text?: string; image?: { asset?: { _ref: string; _type: "reference" }; _type: "image" }; secondary?: string }
    | { _key: string; _type: "resultsCredits"; results?: string; credits?: string }
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type HslColorObject = {
  h?: number;
  s?: number;
  l?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  rampStart?: HslColorObject;
  rampEnd?: HslColorObject;
  gradientBackdrop?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type AllSanitySchemaTypes =
  | WorkProject
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/queries.ts
// Variable: WORK_PROJECTS_QUERY
// Query: *[_type == "workProject"] | order(date desc) { _id, brand, project, category, date, "image": image.asset->url, blocks[] { "type": _type, variant, label, size, text, secondary, results, credits, "image": image.asset->url, "images": images[].asset->url } }
export type WORK_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  brand: string | null;
  project: string | null;
  category: string | null;
  date: string | null;
  image: string | null;
  blocks: Array<{
    type: string | null;
    variant: string | null;
    label: string | null;
    size: string | null;
    text: string | null;
    secondary: string | null;
    results: string | null;
    credits: string | null;
    image: string | null;
    images: (string | null)[] | null;
  }> | null;
}>;

// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] { rampStart { h, s, l }, rampEnd { h, s, l }, "gradientBackdrop": gradientBackdrop.asset->url }
export type SITE_SETTINGS_QUERY_RESULT = {
  rampStart: { h: number | null; s: number | null; l: number | null } | null;
  rampEnd: { h: number | null; s: number | null; l: number | null } | null;
  gradientBackdrop: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "workProject"] | order(date desc) {\n    _id,\n    brand,\n    project,\n    category,\n    date,\n    "image": image.asset->url,\n    blocks[] {\n      "type": _type,\n      variant,\n      label,\n      size,\n      text,\n      secondary,\n      results,\n      credits,\n      "image": image.asset->url,\n      "images": images[].asset->url\n    }\n  }\n': WORK_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0] {\n    rampStart { h, s, l },\n    rampEnd { h, s, l },\n    "gradientBackdrop": gradientBackdrop.asset->url\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
